permissions: write-all
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: install python packages
      run: 'python -m pip install --upgrade pip
        pip install -r requirements.txt
        '
    - env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        GITHUB_TOKEN: ${{ secrets.SECRETS_GITHUB_TOKEN }}
      name: execute py script
      run: "if [[ ${{ github.event_name }} == 'push' ]]; then\n  python three_line_pattern_detect.py\
        \ \"60minute\"\nelif [[ ${{ github.event_name }} == 'schedule' ]]; then\n\
        \  python three_line_pattern_detect.py \"60minute\"\nfi\n"
    - name: commit files
      run: 'git config --local user.email "action@github.com"

        git config --local user.name "GitHub Action"

        git add -A

        git diff-index --quiet HEAD || (git commit -a -m "60 minute.yaml completed"
        --allow-empty)
        '
    - name: fetch changes
      run: git fetch origin
    - name: merge changes
      run: git merge origin/main
    - name: push changes
      run: |
          git push https://github.com/mailblogger2021/line_alerts.git main
      # with:
      #   branch: main
      #   github_token: ${{ secrets.SECRETS_GITHUB_TOKEN }}
name: 60 minute three_line_pattern_detect
'on':
  push:
    branches:
    - main
  schedule:
  - cron: 22 21 16 5 *
  - cron: 45 15 * * mon-fri
