permissions: write-all
name: manual alert
on:
  push:
    branches:
    - main
  # schedule:
  #   - cron: '10 5-11 * * 1-5'    # Mon-Fri hourly from 5:10 to 11:10
  #   - cron: '30 10 * * 1-5'      # Daily at 10:30 Mon-Fri
  #   - cron: '30 10 * * 3,5'      # Weekly on Wednesday and Friday at 10:30
  #   - cron: '30 10 15,30 * *'    # Twice a month on the 15th and 30th at 10:30
  #   - cron: '30 10 1 1,4,7,10 *' # Quarterly on the 1st of Jan, Apr, Jul, Oct at 10:30
jobs:
  build:
    runs-on: macos-latest
    steps:

    - name: Checkout repo content
      uses: actions/checkout@v2

    - name: Check commit message
      id: commit_message_check
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

    - name: Echo commit message
      run: |
        echo "Commit message: ${{ env.COMMIT_MESSAGE }}"

    - name: Set commit message flag
      id: commit_message_flag
      run: |
        if [[ "${{ env.COMMIT_MESSAGE }}" != *"alert"* && "${{ env.COMMIT_MESSAGE }}" != *"all"* ]]; then
          echo "COMMIT_MESSAGE_VALID=false" >> $GITHUB_ENV
        else
          echo "COMMIT_MESSAGE_VALID=true" >> $GITHUB_ENV
        fi

    - name: Setup Python
      if: env.COMMIT_MESSAGE_VALID == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python packages
      if: env.COMMIT_MESSAGE_VALID == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      if: env.COMMIT_MESSAGE_VALID == 'true'
      run: |
          python manual_alert.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "break out stock.yaml completed" --allow-empty)

    - name: Fetch changes
      run: git fetch origin

    - name: Merge changes
      run: git merge origin/main

    - name: Push changes
      run: git push https://github.com/mailblogger2021/line_breakouts.git main
