permissions: write-all
name: PH PL value
on:
  push:
    branches:
    - main
  schedule:
    # - cron: 31 9-16 * * mon-fri  #1hr
    - cron: 0 16 * * mon-fri  # 1d
    - cron: 0 16 * * 3,5      # 1wk
    - cron: 0 16 10,20,30 * * # 1 mo 
    - cron: 0 16 1 * *        # 3 mo
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Determine the schedule
      id: schedule
      run: |
        if [[ "${{ github.event.schedule }}" == '0 16 * * mon-fri' ]]; then
          echo "SCHEDULE_TYPE=day" >> $GITHUB_ENV
        elif [[ "${{ github.event.schedule }}" == '0 16 * * 3,5' ]]; then
          echo "SCHEDULE_TYPE=week" >> $GITHUB_ENV
        elif [[ "${{ github.event.schedule }}" == '0 0 1 * *' ]]; then
          echo "SCHEDULE_TYPE=month" >> $GITHUB_ENV
        elif [[ "${{ github.event.schedule }}" == '0 16 1 * *' ]]; then
          echo "SCHEDULE_TYPE=quarter" >> $GITHUB_ENV
        fi

    - name: Run Python script based on schedule
      run: |
        if [[ "${SCHEDULE_TYPE}" == "day" ]]; then
          python PH_PL_chartink.py "day"
        elif [[ "${SCHEDULE_TYPE}" == "week" ]]; then
          python PH_PL_chartink.py "week"
        elif [[ "${SCHEDULE_TYPE}" == "month" ]]; then
          python PH_PL_chartink.py "month"
        elif [[ "${SCHEDULE_TYPE}" == "quarter" ]]; then
          python PH_PL_chartink.py "quarter"
        elif [[ "${{ github.event_name }}" == 'push' ]]; then
          python PH_PL_chartink.py "day,week,month,quarter"
        fi

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "daily.yaml completed" --allow-empty)

    - name: Fetch changes
      run: git fetch origin

    - name: Merge changes
      run: git merge origin/main

    - name: Push changes
      run: git push https://github.com/mailblogger2021/line_alerts.git main
